service: dev-cox-webhook-messenger-1-1-4
provider:
    name: aws
    role: arn:aws:iam::047632847397:role/acct-managed/lambdarole
    runtime: nodejs12.x
    stage: dev
    region: us-east-1
    environment:
        SERVERLESS: 'true'
functions:
    app:
        handler: app/index.handler
        timeout: 30
        environment:
            RALLY_API_KEY: '${env:RALLY_API_KEY}'
            RALLY_SUBSCRIPTION_ID: '${env:RALLY_SUBSCRIPTION_ID}'
            WEBHOOK_LISTENER_PATH: '${env:WEBHOOK_LISTENER_PATH}'
        events:
            - {http: {path: '${env:WEBHOOK_LISTENER_PATH}/${file(./package.json):version}', method: post}}
            - {http: {path: '${env:WEBHOOK_LISTENER_PATH}/${file(./package.json):version}', method: get}}
plugins:
    - serverless-offline
